version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: bobs-corn-db-only
    environment:
      POSTGRES_DB: bobs_corn_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bobs-corn-network

  redis:
    image: redis:7-alpine
    container_name: bobs-corn-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bobs-corn-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  bobs-corn-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: