version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: bobs-corn-db
    environment:
      POSTGRES_DB: bobs_corn_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: bobs-corn-backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@database:5432/bobs_corn_db
    ports:
      - "3001:3001"
    depends_on:
      - database

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    container_name: bobs-corn-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: